#
# @autor: Cristian Machado <cristian.machado@correounivalle.edu.co>
# @copyrigth: 2024
# @license: GPL-3.0
# TODO: Falta investigar como hacer la parte de los volumenes en kubernetes y el puerto del servicio

apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservices
  labels:
    app: redWheels
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redWheels
  template:
    metadata:
      labels:
        app: redWheels
    spec:
      containers:
        # Ms User db
        - name: ms-user-db
          image: postgres:15.5
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          volumeMounts:
            - name: user-db-vm
              mountPath: /docker-entrypoint-initdb.d

      # Volumes
      volumes:
        - name: user-db-vm
          hostPath:
            path: /app/db/ms-user/
            type: Directory
