#
# @autor: Cristian Machado <cristian.machado@correounivalle.edu.co>
# @copyrigth: 2024
# @license: GPL-3.0
# TODO: Falta investigar como hacer la parte de los volumenes en kubernetes y el puerto del servicio

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redWheelsMs
  labels:
    app: redWheels
spec:
  replicas: 5
  selector:
    matchLabels:
      app: redWheels
  template:
    metadata:
      labels:
        app: redWheels
    spec:
      containers:
      - name:  redWheels-ms-user-server
        image: cristiank/ms_user_server:latest
        ports:
        - containerPort: 4700
        env:
        - name: DB_HOST
          value: ""
        - name: DB_PORT
          value: ""
        - name: DB_NAME
          value: ""
        - name: DB_USER
          value: ""
        - name: DB_PASSWORD
          value: ""
          
      - name:  redWheels-ms-user-db
        image: cristiank/ms_user_db:latest
        ports:
        - containerPort: 5432