#
# @autor: Cristian Machado <cristian.machado@correounivalle.edu.co>
# @copyrigth: 2024
# @license: GPL-3.0
#

apiVersion: v1
kind: Service
metadata:
  name: microservices-service
spec:
  selector:
    app: redWheels
  ports:
    - name: kafka-port
      port: 9092
      targetPort: 9092
    - name: db-port-user
      protocol: TCP
      port: 5432
      targetPort: 5432
    - name: server-port-user
      protocol: TCP
      port: 4700
      targetPort: 4700
    - name: server-port-products
      protocol: TCP
      port: 4701
      targetPort: 4701
    - name: db-port-products
      protocol: TCP
      port: 5433
      targetPort: 5432
