services:
  nginx:
    image: nginx:latest
    ports:
      - "4701:4700"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./sites-available:/etc/nginx/sites-available
      - ./sites-enabled:/etc/nginx/sites-enabled