#
# @autor: Cristian Machado <cristian.machado@correounivalle.edu.co>
# @copyrigth: 2024
# @license: GPL-3.0
#

apiVersion: v1
kind: Pod
metadata:
  name: ms-products-pod
  labels:
    app: bd-products
spec:
  containers:
    - name: ms-products-db
      image: postgres:15.5
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
      volumeMounts:
        - name: ms-products-vm
          mountPath: /docker-entrypoint-initdb.d
  volumes:
    - name: ms-products-vm
      persistentVolumeClaim:
        claimName: product-db-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: ms-products-service
spec:
  selector:
    app: bd-products
  ports:
    - protocol: TCP
      port: 5433
      targetPort: 5432
  type: ClusterIP
